version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout
      # Mavenのキャッシュを設定
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven
      - run:
          name: Maven Build
          command: mvn -B -DskipTests=true package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
          # キャッシュの有効期限を設定
          expires: 1d
      # アーティファクトをアップロードするステップ
      - run:
          name: Upload to Github Packages
          command: |
            echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">" > ~/.m2/settings.xml
            echo "<servers>" >> ~/.m2/settings.xml
            echo "<server>" >> ~/.m2/settings.xml
            echo "<id>github</id>" >> ~/.m2/settings.xml
            echo "<username>${GITHUB_REPOSITORY_OWNER}</username>" >> ~/.m2/settings.xml
            echo "<password>${TEST_TOKEN}</password>" >> ~/.m2/settings.xml
            echo "</server>" >> ~/.m2/settings.xml
            echo "</servers>" >> ~/.m2/settings.xml
            echo "</settings>" >> ~/.m2/settings.xml
            mvn deploy
          environment:
            GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
            TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
